# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9fc25fa637018a249454d2d60c9b460128585cc6a08299a5037e83948a4c156f2399644663b46e359a0e55c4604b2a7332b42b8da5400d8ef7f9050f91bb1df0

test:
  secret_key_base: bf7fc37a0f314962ce5c0118ce3bf11d25cca02039b2cd79d5c3b68dffa3ed7dbb09e270cfaa533d3fdda38c92308acf80e8c171a713b5e05cf7456278db7f62

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
